// Builds supabase/seed.sql from website/snapshot/*.json.
// Usage (from repo root): node scripts/make-seed.mjs
import fs from 'node:fs';

const SNAP = 'website/snapshot';
const read = k => JSON.parse(fs.readFileSync(`${SNAP}/${k}.json`, 'utf8'));
const TAG = '$seed$';
const lit = v => {
  const s = JSON.stringify(v);
  if (s.includes(TAG)) throw new Error('data contains the dollar-quote tag');
  return `${TAG}${s}${TAG}::jsonb`;
};

const PUBLIC_DATASETS = ['gear', 'gear-logo-map', 'talents', 'weapon-classes'];
const builds = read('builds');

let out = `-- ============================================================================
-- SHD FIELD TOOLKIT — INITIAL DATA (generated by scripts/make-seed.mjs)
-- Run AFTER schema.sql, in Supabase → SQL Editor. Loads the current site data.
-- Re-running is safe: existing rows are left alone (on conflict do nothing).
-- ============================================================================

begin;

`;
for (const k of PUBLIC_DATASETS) {
  const d = read(k);
  out += `-- ${k}: ${Array.isArray(d) ? d.length + ' items' : Object.keys(d).length + ' keys'}\n`;
  out += `insert into public.datasets (key, data, published, updated_by)\nvalues ('${k}', ${lit(d)}, true, 'seed')\non conflict (key) do nothing;\n\n`;
}
out += `-- builds: ${builds.length}, all published, in the order they appear on the Builds page\n`;
builds.forEach((b, i) => {
  out += `insert into public.builds (id, category, status, sort_order, data, updated_by)\n` +
         `values ('${b.id.replace(/'/g, "''")}', '${b.cat}', 'published', ${(i + 1) * 10}, ${lit(b)}, 'seed')\n` +
         `on conflict (id) do nothing;\n`;
});
out += `\ncommit;\n\n-- Check: should list 4 datasets and ${builds.length} builds\n` +
       `select 'datasets' as tbl, count(*) from public.datasets\nunion all\nselect 'builds', count(*) from public.builds;\n`;

fs.mkdirSync('supabase', { recursive: true });
fs.writeFileSync('supabase/seed.sql', out);
console.log('wrote supabase/seed.sql', (out.length / 1024).toFixed(0) + ' KB');
